# Generated by Django 4.1 on 2022-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyLocation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('durationForm', models.CharField(max_length=50)),
                ('durationTo', models.CharField(max_length=50)),
            ],
        ),
    ]
