# Generated by Django 4.1 on 2022-09-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_portfolio', '0002_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='durationForm',
            new_name='durationFrom',
        ),
    ]
