# Generated by Django 4.1 on 2022-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_portfolio', '0003_rename_durationform_experience_durationfrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=50)),
                ('livesite', models.CharField(max_length=50)),
            ],
        ),
    ]
