# Generated by Django 4.1 on 2022-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_portfolio', '0004_workdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
